data = [
    {"mandarin": "一见钟情", "english": "Love at first sight"},
    {"mandarin": "以眼还眼，以牙还牙", "english": "An eye for an eye, a tooth for a tooth"},
    {"mandarin": "如鱼得水", "english": "Like fish in the water"},
    {"mandarin": "一箭双雕/一石二鸟/一举两得", "english": "Killing two birds with one stone"},
    {"mandarin": "夜以继日", "english": "Day and night"},
    {"mandarin": "九牛一毛", "english": "A drop in the ocean"},
    {"mandarin": "披着羊皮的狼", "english": "Wolf in sheep’s clothing"},
    {"mandarin": "有志者事竟成", "english": "Where there’s a will, there’s a way"},
    {"mandarin": "不翼而飞", "english": "To vanish into thin air"},
    {"mandarin": "说曹操，曹操到", "english": "Speak of the devil"},
    {"mandarin": "入乡随俗", "english": "When in Rome, do as the Romans"},
    {"mandarin": "塞翁失马，焉知非福/因祸得福", "english": "A blessing in disguise"},
    {"mandarin": "萝卜青菜，各有所爱", "english": "To each his own"},
    {"mandarin": "人不可貌相", "english": "Can't judge a book by its cover"},
    {"mandarin": "五十步笑百步", "english": "Pot calls the kettle black"},
    {"mandarin": "一口吃不成胖子", "english": "Rome wasn't build in a day"},
    {"mandarin": "好久不见", "english": "Long time no see"},
    {"mandarin": "半途而废", "english": "To give up halfway"},
    {"mandarin": "抛砖引玉", "english": "Tossing out an idea"},
    {"mandarin": "理所当然", "english": "Taken for granted"},
    {"mandarin": "心血来潮", "english": "Spur of the moment"},
    {"mandarin": "虎头蛇尾/高开低走", "english": "Start strong but finish weak"},
    {"mandarin": "冰山一角", "english": "The tip of an iceberg"},
    {"mandarin": "拭目以待", "english": "Wait and see"},
    {"mandarin": "左右为难", "english": "In a dilemma"},
    {"mandarin": "顾客就是上帝", "english": "The customer is always right"},
    {"mandarin": "三思而后行", "english": "Think before you act"},
    {"mandarin": "种瓜得瓜，种豆得豆/自食其果", "english": "You reap what you sow"},
    {"mandarin": "祸不单行/屋漏偏逢连夜雨", "english": "When it rains, it pours"},
    {"mandarin": "未雨绸缪", "english": "To prepare for a rainy day"},
    {"mandarin": "一朝被蛇咬，十年怕井绳", "english": "Once bitten, twice shy"},
    {"mandarin": "老虎不在家，猴子称大王/山高皇帝远", "english": "When the cat’s away, the mice will play"},
    {"mandarin": "火上浇油/雪上加霜", "english": "Add fuel to the fire"},
    {"mandarin": "力所能及", "english": "Within one's powers"},
    {"mandarin": "得天独厚", "english": "favored by nature"},
    {"mandarin": "锦上添花", "english": "Icing on the cake"},
    {"mandarin": "鸦雀无声", "english": "So quiet you can hear a pin drop"},
    {"mandarin": "画蛇添足", "english": "To overdo something"},
    {"mandarin": "苦尽甘来", "english": "April showers bring May flowers"},
    {"mandarin": "优胜劣汰", "english": "Survival of the fittest"},
    {"mandarin": "以其人之道还治其人之身", "english": "To beat someone at their own game"},
    {"mandarin": "以防万一", "english": "Just in case"},
    {"mandarin": "暗箭伤人", "english": "Stab someone in the back"},
    {"mandarin": "旗鼓相当", "english": "Evenly matched"},
    {"mandarin": "有其父必有其子", "english": "Like father, like son"},
    {"mandarin": "吃一堑，长一智", "english": "You live and you learn"},
    {"mandarin": "独一无二", "english": "One of a kind"},
    {"mandarin": "江山易改，本性难移", "english": "A leopard never changes its spots"},
    {"mandarin": "无计可施", "english": "At one's wits' end"},
    {"mandarin": "青梅竹马", "english": "Childhood sweetheart"},
    {"mandarin": "班门弄斧", "english": "To teach a fish how to swim/Show off one's skill before an expert"},
    {"mandarin": "花开堪折直须折", "english": "Gather ye rosebuds while ye may"},
    {"mandarin": "是可忍，孰不可忍", "english": "Enough is enough"},
    {"mandarin": "随心所欲", "english": "To do as one pleases"},
    {"mandarin": "木已成舟/生米煮成熟饭", "english": "What's done is done"},
    {"mandarin": "有福同享，有难同当", "english": "For better or for worse"},
    {"mandarin": "千篇一律", "english": "Once you have seen one, you have seen them all"},
    {"mandarin": "忍无可忍", "english": "The last straw"},
    {"mandarin": "滚瓜烂熟", "english": "To know something by heart"},
    {"mandarin": "先礼后兵", "english": "Diplomacy before violence"},
    {"mandarin": "幸灾乐祸", "english": "Take pleasure in the misfortunes of others"},
    {"mandarin": "安然无恙", "english": "Safe and sound"},
    {"mandarin": "立竿见影", "english": "To get instant results"},
    {"mandarin": "不见不散", "english": "Be there or be square"},
    {"mandarin": "胡思乱想", "english": "To let one's imagination run wild"},
    {"mandarin": "猝不及防", "english": "Catch someone off guard"},
    {"mandarin": "知己知彼", "english": "Know yourself and know your enemies"},
    {"mandarin": "得寸进尺", "english": "Push one's luck"},
    {"mandarin": "不速之客", "english": "Uninvited guest"},
    {"mandarin": "千方百计/不遗余力", "english": "Leave no stone unturned"},
    {"mandarin": "开门见山", "english": "To get right to the point"},
    {"mandarin": "竹篮打水一场空", "english": "Wasted effort"},
]
